### ISSUE TITLE
Uncaught (in promise) TypeError

### ISSUE THREAD

**Issue by almereyda** [cabal-club/cabal-desktop#113]
After the downgrade of Electron https://github.com/cabal-club/cabal-desktop/commit/694925c018518e9ab9340fd6ce3c7655b9e0f4a5 we observed little successory regressions in the aftermath of #110 and they got fixed with https://github.com/cabal-club/cabal-desktop/commit/79983a5f375665806265bd9522d3e940f4b6a2ab

`cabal-desktop` would be usable through `npm start` before, but now degraded again. DevTools hint at

```
Uncaught (in promise) TypeError: cabal.db.ready is not a function
    at initializeCabal (actions.js:261)
    at dispatch (actions.js:186)
    at /home/yala/src/github.com/cabal-club/cabal-desktop/node_modules/redux-thunk/lib/index.js:11
    at dispatch (/home/yala/src/github.com/cabal-club/cabal-desktop/node_modules/redux/lib/redux.js:617)
    at _dispatch_add_cabal (actions.js:405)
    at iterateCabals (actions.js:397)
    at eval (actions.js:411)
    at <anonymous>
```

Selecting text in these DevTools might also crash the Electron instance, as seen on Fedora 30 with Node 10.15.

Is anybody able to reproduce this issue?

**Comment by karissa** [comment]
Yes this is because of a recent release of cabal-core that changed the api cc @noffle @substack

**Comment by karissa** [comment]
use `cabal.ready` instead of cabal.db.ready @nikolaiwarner

**Comment by karissa** [comment]
closed in https://github.com/cabal-club/cabal-desktop/commit/0c8573b3d50ce8bc6684d51e575d4d6a4b03984b

**Comment by nikolaiwarner** [comment]
thanks @karissa !!

**Comment by almereyda** [comment]
Many thanks, confirmed to work again as intended.
